// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bigText: string;
  blackText: string;
  btnWrapper: string;
  imageWrapper: string;
  root: string;
  smallText: string;
}
export const cssExports: CssExports;
export default cssExports;
